//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.269
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.269.
// 
#pragma warning disable 1591

namespace AndroidApplication01.AndroidServices {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Services1Soap", Namespace="http://tempuri.org/")]
    public partial class Services1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserValidationJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserValidationXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAssociatedServicesJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAssociatedServicesXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReporteConsumoJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReporteConsumoXMLOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Services1() {
            this.Url = "http://localhost:8080/AppMobile.Web.Services/Services.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event GetUserValidationJSONCompletedEventHandler GetUserValidationJSONCompleted;
        
        /// <remarks/>
        public event GetUserValidationXMLCompletedEventHandler GetUserValidationXMLCompleted;
        
        /// <remarks/>
        public event GetAssociatedServicesJSONCompletedEventHandler GetAssociatedServicesJSONCompleted;
        
        /// <remarks/>
        public event GetAssociatedServicesXMLCompletedEventHandler GetAssociatedServicesXMLCompleted;
        
        /// <remarks/>
        public event GetReporteConsumoJSONCompletedEventHandler GetReporteConsumoJSONCompleted;
        
        /// <remarks/>
        public event GetReporteConsumoXMLCompletedEventHandler GetReporteConsumoXMLCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserValidationJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetUserValidationJSON(string Rut, string Pass) {
            object[] results = this.Invoke("GetUserValidationJSON", new object[] {
                        Rut,
                        Pass});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserValidationJSONAsync(string Rut, string Pass) {
            this.GetUserValidationJSONAsync(Rut, Pass, null);
        }
        
        /// <remarks/>
        public void GetUserValidationJSONAsync(string Rut, string Pass, object userState) {
            if ((this.GetUserValidationJSONOperationCompleted == null)) {
                this.GetUserValidationJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserValidationJSONOperationCompleted);
            }
            this.InvokeAsync("GetUserValidationJSON", new object[] {
                        Rut,
                        Pass}, this.GetUserValidationJSONOperationCompleted, userState);
        }
        
        private void OnGetUserValidationJSONOperationCompleted(object arg) {
            if ((this.GetUserValidationJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserValidationJSONCompleted(this, new GetUserValidationJSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserValidationXML", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetUserValidationXML(string Rut, string Pass) {
            object[] results = this.Invoke("GetUserValidationXML", new object[] {
                        Rut,
                        Pass});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserValidationXMLAsync(string Rut, string Pass) {
            this.GetUserValidationXMLAsync(Rut, Pass, null);
        }
        
        /// <remarks/>
        public void GetUserValidationXMLAsync(string Rut, string Pass, object userState) {
            if ((this.GetUserValidationXMLOperationCompleted == null)) {
                this.GetUserValidationXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserValidationXMLOperationCompleted);
            }
            this.InvokeAsync("GetUserValidationXML", new object[] {
                        Rut,
                        Pass}, this.GetUserValidationXMLOperationCompleted, userState);
        }
        
        private void OnGetUserValidationXMLOperationCompleted(object arg) {
            if ((this.GetUserValidationXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserValidationXMLCompleted(this, new GetUserValidationXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAssociatedServicesJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAssociatedServicesJSON(long IdUsuarioWeb) {
            object[] results = this.Invoke("GetAssociatedServicesJSON", new object[] {
                        IdUsuarioWeb});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAssociatedServicesJSONAsync(long IdUsuarioWeb) {
            this.GetAssociatedServicesJSONAsync(IdUsuarioWeb, null);
        }
        
        /// <remarks/>
        public void GetAssociatedServicesJSONAsync(long IdUsuarioWeb, object userState) {
            if ((this.GetAssociatedServicesJSONOperationCompleted == null)) {
                this.GetAssociatedServicesJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAssociatedServicesJSONOperationCompleted);
            }
            this.InvokeAsync("GetAssociatedServicesJSON", new object[] {
                        IdUsuarioWeb}, this.GetAssociatedServicesJSONOperationCompleted, userState);
        }
        
        private void OnGetAssociatedServicesJSONOperationCompleted(object arg) {
            if ((this.GetAssociatedServicesJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAssociatedServicesJSONCompleted(this, new GetAssociatedServicesJSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAssociatedServicesXML", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAssociatedServicesXML(long IdUsuarioWeb) {
            object[] results = this.Invoke("GetAssociatedServicesXML", new object[] {
                        IdUsuarioWeb});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAssociatedServicesXMLAsync(long IdUsuarioWeb) {
            this.GetAssociatedServicesXMLAsync(IdUsuarioWeb, null);
        }
        
        /// <remarks/>
        public void GetAssociatedServicesXMLAsync(long IdUsuarioWeb, object userState) {
            if ((this.GetAssociatedServicesXMLOperationCompleted == null)) {
                this.GetAssociatedServicesXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAssociatedServicesXMLOperationCompleted);
            }
            this.InvokeAsync("GetAssociatedServicesXML", new object[] {
                        IdUsuarioWeb}, this.GetAssociatedServicesXMLOperationCompleted, userState);
        }
        
        private void OnGetAssociatedServicesXMLOperationCompleted(object arg) {
            if ((this.GetAssociatedServicesXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAssociatedServicesXMLCompleted(this, new GetAssociatedServicesXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetReporteConsumoJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetReporteConsumoJSON(long IdServicio) {
            object[] results = this.Invoke("GetReporteConsumoJSON", new object[] {
                        IdServicio});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetReporteConsumoJSONAsync(long IdServicio) {
            this.GetReporteConsumoJSONAsync(IdServicio, null);
        }
        
        /// <remarks/>
        public void GetReporteConsumoJSONAsync(long IdServicio, object userState) {
            if ((this.GetReporteConsumoJSONOperationCompleted == null)) {
                this.GetReporteConsumoJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReporteConsumoJSONOperationCompleted);
            }
            this.InvokeAsync("GetReporteConsumoJSON", new object[] {
                        IdServicio}, this.GetReporteConsumoJSONOperationCompleted, userState);
        }
        
        private void OnGetReporteConsumoJSONOperationCompleted(object arg) {
            if ((this.GetReporteConsumoJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReporteConsumoJSONCompleted(this, new GetReporteConsumoJSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetReporteConsumoXML", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetReporteConsumoXML(long IdServicio) {
            object[] results = this.Invoke("GetReporteConsumoXML", new object[] {
                        IdServicio});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetReporteConsumoXMLAsync(long IdServicio) {
            this.GetReporteConsumoXMLAsync(IdServicio, null);
        }
        
        /// <remarks/>
        public void GetReporteConsumoXMLAsync(long IdServicio, object userState) {
            if ((this.GetReporteConsumoXMLOperationCompleted == null)) {
                this.GetReporteConsumoXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReporteConsumoXMLOperationCompleted);
            }
            this.InvokeAsync("GetReporteConsumoXML", new object[] {
                        IdServicio}, this.GetReporteConsumoXMLOperationCompleted, userState);
        }
        
        private void OnGetReporteConsumoXMLOperationCompleted(object arg) {
            if ((this.GetReporteConsumoXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReporteConsumoXMLCompleted(this, new GetReporteConsumoXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetUserValidationJSONCompletedEventHandler(object sender, GetUserValidationJSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserValidationJSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserValidationJSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetUserValidationXMLCompletedEventHandler(object sender, GetUserValidationXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserValidationXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserValidationXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAssociatedServicesJSONCompletedEventHandler(object sender, GetAssociatedServicesJSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAssociatedServicesJSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAssociatedServicesJSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAssociatedServicesXMLCompletedEventHandler(object sender, GetAssociatedServicesXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAssociatedServicesXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAssociatedServicesXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetReporteConsumoJSONCompletedEventHandler(object sender, GetReporteConsumoJSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReporteConsumoJSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReporteConsumoJSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetReporteConsumoXMLCompletedEventHandler(object sender, GetReporteConsumoXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReporteConsumoXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReporteConsumoXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591