//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.269
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroidApplication01
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050007
			public const int MyButton = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int Sp = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int btnIngresar = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int tvEstado = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int tvPass = 2131034115;
			
			// aapt resource value: 0x7f05000a
			public const int tvSp = 2131034122;
			
			// aapt resource value: 0x7f050001
			public const int tvUsuario = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int txtPass = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int txtUsuario = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int widget62 = 2131034120;
			
			// aapt resource value: 0x7f050000
			public const int widget65 = 2131034112;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int FormExample = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int linear = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int SpinerExample = 2130903043;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			private String()
			{
			}
		}
	}
}
